name: 테스트 실행

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.11]
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v4
    
    - name: Python ${{ matrix.python-version }} 설정
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt
    
    - name: 린터 실행 (flake8)
      run: |
        pip install flake8
        cd backend
        # 구문 오류나 정의되지 않은 이름이 있으면 중단
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # 경고는 GitHub 에디터에서 issue로 처리하지만 실패시키지 않음
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: 테스트 실행 (pytest)
      run: |
        cd backend
        python -m pytest tests/ -v --tb=short
      env:
        PYTHONPATH: ${{ github.workspace }}/backend 